---
- name: Push petclinic to hosts
  hosts: devops_hw2
  remote_user: vagrant

  tasks:
          - name: Copy jar to remote host
            copy:
                    src: /var/lib/jenkins/workspace/spring-petclinic_main
                    dest: ~/petclinic
                    owner: vagrant
                    group: vagrant
                    mode: '0774'

          - name: run jar
            shell:
                    "mvn spring-boot:run"
            args:
                    chdir: "~/petclinic/spring-petclinic_main"
